# Generated by Django 4.2.5 on 2023-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRCA1Breast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BRCA1Ovarine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BRCA2Breast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BRCA2Ovarine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PALB2Breast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PALB2Ovarine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('averageTen', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentile', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('averageLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lowerCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('upperCentileLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('residualLifetime', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
    ]
