# Generated by Django 4.2.5 on 2023-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplan_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brca1breast',
            name='age',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
